# Default values for mfbackend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
stage: dev

image:
  repository: 192.168.100.73:31003/repository/mydockerrepo/holgerfischer/myfinance-
  pullPolicy: IfNotPresent


pv:
  mntpath: /mnt/data/mf/
  configpvc: mffeconfigpvc
  configstorage: _mffe_config/
  configstoragesize: 1Mi

mffrontend:
  name: mffrontend
  http_port_ext: 30023
  http_port: 80

ingress:
  enabled: true
  prefix: .
  postfix: .mylocaldomain
  host: mffe
