# Default values for mfbackend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 192.168.100.73:31003/repository/mydockerrepo/holgerfischer/myfinance-
  pullPolicy: IfNotPresent


pv:
  configpvc: mffeconfigpvc
  configstorage: /mnt/data/mf/prod_mffe_config/
  configstoragesize: 1Mi

mffrontend:
  name: mffrontend
  http_port_ext: 30022
  http_port: 80

ingress:
  enabled: true
  host: fe.myfinance.mylocaldomain   
