{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.mffrontend.name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: {{ .Values.stage }}{{ .Values.ingress.prefix }}{{ .Values.ingress.host }}{{ .Values.ingress.postfix }} #for local use add these domain to your dns server for example sophos-network-dns-DNS Host Entry. 
      http:
        paths:
        - path: /
          backend:
            serviceName: {{ .Values.mffrontend.name }}    
            servicePort: {{ .Values.mffrontend.http_port }}
{{- end }}

