/**
 * Dac Services
 * Dac Service REST API
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InstrumentListResource } from './instrumentListResource';
import { RecurrentTransactionListResource } from './recurrentTransactionListResource';
import { TenantListResource } from './tenantListResource';


export interface EnvironmentDataResource {
    instruments?: InstrumentListResource;
    recurrentTransaction?: RecurrentTransactionListResource;
    tenants?: TenantListResource;
}
