/**
 * Dac Services
 * Dac Service REST API
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Instrument {
    instrumentid: number;
    description: string;
    isactive: boolean;
    maturitydate?: string;
    closingdate?: string;
    treelastchanged: Date;
    instrumentType: Instrument.InstrumentTypeEnum;
    businesskey?: string;
}
export namespace Instrument {
    export type InstrumentTypeEnum = 'Giro' | 'MoneyAtCall' | 'TimeDeposit' | 'BuildingsavingAccount' | 'Budget' | 'Tenant' | 'AccountPortfolio' | 'ArtificialPortfolio' | 'BudgetGroup' | 'Depot' | 'Buildingsaving' | 'Currency' | 'Equity' | 'Fonds' | 'ETF' | 'Index' | 'Bond' | 'LifeInsurance' | 'DepreciationObject' | 'RealEstate' | 'Loan' | 'UNKNOWN';
    export const InstrumentTypeEnum = {
        Giro: 'Giro' as InstrumentTypeEnum,
        MoneyAtCall: 'MoneyAtCall' as InstrumentTypeEnum,
        TimeDeposit: 'TimeDeposit' as InstrumentTypeEnum,
        BuildingsavingAccount: 'BuildingsavingAccount' as InstrumentTypeEnum,
        Budget: 'Budget' as InstrumentTypeEnum,
        Tenant: 'Tenant' as InstrumentTypeEnum,
        AccountPortfolio: 'AccountPortfolio' as InstrumentTypeEnum,
        ArtificialPortfolio: 'ArtificialPortfolio' as InstrumentTypeEnum,
        BudgetGroup: 'BudgetGroup' as InstrumentTypeEnum,
        Depot: 'Depot' as InstrumentTypeEnum,
        Buildingsaving: 'Buildingsaving' as InstrumentTypeEnum,
        Currency: 'Currency' as InstrumentTypeEnum,
        Equity: 'Equity' as InstrumentTypeEnum,
        Fonds: 'Fonds' as InstrumentTypeEnum,
        ETF: 'ETF' as InstrumentTypeEnum,
        Index: 'Index' as InstrumentTypeEnum,
        Bond: 'Bond' as InstrumentTypeEnum,
        LifeInsurance: 'LifeInsurance' as InstrumentTypeEnum,
        DepreciationObject: 'DepreciationObject' as InstrumentTypeEnum,
        RealEstate: 'RealEstate' as InstrumentTypeEnum,
        Loan: 'Loan' as InstrumentTypeEnum,
        UNKNOWN: 'UNKNOWN' as InstrumentTypeEnum
    }
}
