/**
 * Dac Services
 * Dac Service REST API
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Instrument { 
    instrumentid: number;
    instrumentType: Instrument.InstrumentTypeEnum;
    description: string;
    isactive: boolean;
    maturitydate?: string;
    closingdate?: string;
    treelastchanged: Date;
    businesskey?: string;
}
export namespace Instrument {
    export type InstrumentTypeEnum = 'GIRO' | 'MONEYATCALL' | 'TIMEDEPOSIT' | 'BUILDINGSAVINGACCOUNT' | 'BUDGET' | 'TENANT' | 'ACCOUNTPORTFOLIO' | 'ARTIFICALPORTFOLIO' | 'BUDGETGROUP' | 'DEPOT' | 'BUILDINGSAVING' | 'CURRENCY' | 'EQUITY' | 'FONDS' | 'ETF' | 'INDEX' | 'BOND' | 'LIFEINSURANCE' | 'DEPRECATIONOBJECT' | 'REALESTATE' | 'LOAN' | 'BUDGETPORTFOLIO' | 'UNKNOWN';
    export const InstrumentTypeEnum = {
        GIRO: 'GIRO' as InstrumentTypeEnum,
        MONEYATCALL: 'MONEYATCALL' as InstrumentTypeEnum,
        TIMEDEPOSIT: 'TIMEDEPOSIT' as InstrumentTypeEnum,
        BUILDINGSAVINGACCOUNT: 'BUILDINGSAVINGACCOUNT' as InstrumentTypeEnum,
        BUDGET: 'BUDGET' as InstrumentTypeEnum,
        TENANT: 'TENANT' as InstrumentTypeEnum,
        ACCOUNTPORTFOLIO: 'ACCOUNTPORTFOLIO' as InstrumentTypeEnum,
        ARTIFICALPORTFOLIO: 'ARTIFICALPORTFOLIO' as InstrumentTypeEnum,
        BUDGETGROUP: 'BUDGETGROUP' as InstrumentTypeEnum,
        DEPOT: 'DEPOT' as InstrumentTypeEnum,
        BUILDINGSAVING: 'BUILDINGSAVING' as InstrumentTypeEnum,
        CURRENCY: 'CURRENCY' as InstrumentTypeEnum,
        EQUITY: 'EQUITY' as InstrumentTypeEnum,
        FONDS: 'FONDS' as InstrumentTypeEnum,
        ETF: 'ETF' as InstrumentTypeEnum,
        INDEX: 'INDEX' as InstrumentTypeEnum,
        BOND: 'BOND' as InstrumentTypeEnum,
        LIFEINSURANCE: 'LIFEINSURANCE' as InstrumentTypeEnum,
        DEPRECATIONOBJECT: 'DEPRECATIONOBJECT' as InstrumentTypeEnum,
        REALESTATE: 'REALESTATE' as InstrumentTypeEnum,
        LOAN: 'LOAN' as InstrumentTypeEnum,
        BUDGETPORTFOLIO: 'BUDGETPORTFOLIO' as InstrumentTypeEnum,
        UNKNOWN: 'UNKNOWN' as InstrumentTypeEnum
    };
}
