/**
 * Dac Services
 * Dac Service REST API
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { StatusChange } from './statusChange';


export interface JobInformation { 
    uuid?: string;
    startTime?: string;
    status?: JobInformation.StatusEnum;
    statusChangeHistory?: Array<StatusChange>;
    payload?: any;
    result?: any;
    statusMessageCollector?: Array<StatusChange>;
    endTime?: string;
}
export namespace JobInformation {
    export type StatusEnum = 'UNKNOWN' | 'QUEUED' | 'PROCESSING' | 'FINISHED' | 'FAILED';
    export const StatusEnum = {
        UNKNOWN: 'UNKNOWN' as StatusEnum,
        QUEUED: 'QUEUED' as StatusEnum,
        PROCESSING: 'PROCESSING' as StatusEnum,
        FINISHED: 'FINISHED' as StatusEnum,
        FAILED: 'FAILED' as StatusEnum
    };
}
