/**
 * Dac Services
 * Dac Service REST API
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Instrument } from './instrument';


export interface RecurrentTransaction { 
    recurrenttransactionid: number;
    instrumentByInstrumentid2: Instrument;
    instrumentBySecurityid: Instrument;
    instrumentByInstrumentid1: Instrument;
    recurrencytype: number;
    description: string;
    value: number;
    nexttransaction: string;
    recurrentfrequenceId: number;
    recurrentfrequence: RecurrentTransaction.RecurrentfrequenceEnum;
}
export namespace RecurrentTransaction {
    export type RecurrentfrequenceEnum = 'Monthly' | 'Quaterly' | 'Yearly' | 'UNKNOWN';
    export const RecurrentfrequenceEnum = {
        Monthly: 'Monthly' as RecurrentfrequenceEnum,
        Quaterly: 'Quaterly' as RecurrentfrequenceEnum,
        Yearly: 'Yearly' as RecurrentfrequenceEnum,
        UNKNOWN: 'UNKNOWN' as RecurrentfrequenceEnum
    };
}
