/**
 * Dac Services
 * Dac Service REST API
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface StatusChange { 
    changeTime?: string;
    oldStatus?: StatusChange.OldStatusEnum;
    newStatus?: StatusChange.NewStatusEnum;
    changeInformation?: string;
}
export namespace StatusChange {
    export type OldStatusEnum = 'UNKNOWN' | 'QUEUED' | 'PROCESSING' | 'FINISHED' | 'FAILED';
    export const OldStatusEnum = {
        UNKNOWN: 'UNKNOWN' as OldStatusEnum,
        QUEUED: 'QUEUED' as OldStatusEnum,
        PROCESSING: 'PROCESSING' as OldStatusEnum,
        FINISHED: 'FINISHED' as OldStatusEnum,
        FAILED: 'FAILED' as OldStatusEnum
    };
    export type NewStatusEnum = 'UNKNOWN' | 'QUEUED' | 'PROCESSING' | 'FINISHED' | 'FAILED';
    export const NewStatusEnum = {
        UNKNOWN: 'UNKNOWN' as NewStatusEnum,
        QUEUED: 'QUEUED' as NewStatusEnum,
        PROCESSING: 'PROCESSING' as NewStatusEnum,
        FINISHED: 'FINISHED' as NewStatusEnum,
        FAILED: 'FAILED' as NewStatusEnum
    };
}
